/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderBar: typeof import('./src/components/frame/HeaderBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconMailOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconMailOutline']
    IconSearchOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconSearchOutline']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/frame/SideMenu.vue')['default']
    TopTitle: typeof import('./src/components/frame/TopTitle.vue')['default']
    YkAvatar: typeof import('@yike-design/ui')['YkAvatar']
    YkBadge: typeof import('@yike-design/ui')['YkBadge']
    YkButton: typeof import('@yike-design/ui')['YkButton']
    YkInputSearch: typeof import('@yike-design/ui')['YkInputSearch']
    YkSpace: typeof import('@yike-design/ui')['YkSpace']
    YkText: typeof import('@yike-design/ui')['YkText']
    YkTheme: typeof import('@yike-design/ui')['YkTheme']
    YkTitle: typeof import('@yike-design/ui')['YkTitle']
  }
}
