/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/comment/Comment.vue')['default']
    DataChart: typeof import('./src/components/content/DataChart.vue')['default']
    Gather: typeof import('./src/components/content/Gather.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderBar: typeof import('./src/components/frame/HeaderBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCrossFill: typeof import('@yike-design/ui/es/components/svg-icon')['IconCrossFill']
    IconLikeFill: typeof import('@yike-design/ui/es/components/svg-icon')['IconLikeFill']
    IconMailOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconMailOutline']
    IconPlusOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconPlusOutline']
    IconSearchOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconSearchOutline']
    Item: typeof import('./src/components/comment/Item.vue')['default']
    LineChart: typeof import('./src/components/echarts/LineChart.vue')['default']
    Message: typeof import('./src/components/comment/Message.vue')['default']
    PersonalLetter: typeof import('./src/components/comment/PersonalLetter.vue')['default']
    PieChart: typeof import('./src/components/echarts/PieChart.vue')['default']
    Review: typeof import('./src/components/comment/Review.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/frame/SideMenu.vue')['default']
    TopTitle: typeof import('./src/components/frame/TopTitle.vue')['default']
    YkAvatar: typeof import('@yike-design/ui')['YkAvatar']
    YkBadge: typeof import('@yike-design/ui')['YkBadge']
    YkButton: typeof import('@yike-design/ui')['YkButton']
    YkInputSearch: typeof import('@yike-design/ui')['YkInputSearch']
    YkRadio: typeof import('@yike-design/ui')['YkRadio']
    YkRadioGroup: typeof import('@yike-design/ui')['YkRadioGroup']
    YkSpace: typeof import('@yike-design/ui')['YkSpace']
    YkTag: typeof import('@yike-design/ui')['YkTag']
    YkText: typeof import('@yike-design/ui')['YkText']
    YkTheme: typeof import('@yike-design/ui')['YkTheme']
    YkTitle: typeof import('@yike-design/ui')['YkTitle']
  }
}
